version: '3'
services:
  edge:
      image: edge
      container_name: edge
      command: uvicorn main:app --host 0.0.0.0 --port 4400 --reload
      ports:
        - "4400:4400"
      volumes:
        - ./IoTeam/hhs/edge:/app
      restart: always